### ISSUE TITLE
v0.1.0 Release Tracker

### ISSUE THREAD

**Issue by expiteRz** [expiteRz/mkw-distro-tool#3]
- [ ] GUI lauout
- [ ] LPAR setting
- [ ] Track definition
- [ ] Track file import
- [ ] Cup icon creation
- [ ] BMG creation
- [ ] Cheat code injection
- [ ] Riivolution package creation
